### ISSUE TITLE
Lista de matches

### ISSUE THREAD

**Issue by hgmart** [el-unico-match/match#12]
Como usuario de Match, quiero ser capaz de ver una lista de los perfiles con los que tuve un match
Criterios de aceptacion

CA 1: Listado de matches
Cuando ingreso a la aplicacion
Entonces tengo acceso a una vista de usuarios con los que hice match
Se listan en orden cronologico o de ultimo chat
CA 2: Ver perfil
Cuanto estoy en la lista de matches
Entonces puedo ingresar al perfil de las personas con las que hice match
CA 3: Chatear
Cuando estoy en la lista de matches
Entonces puedo ingresar al chat con las personas con las que tengo match
CA 4: Listado vacio
Cuando ingreso a la lista de matches y no tengo ningun match aun
Entonces se muestra un mensaje indicando que no hay matches
El mensaje ofrece ir a la vista principal para intentar conseguir matches

**Comment by FontiLucas** [comment]
Falta CA2.
