### ISSUE TITLE
Super Likes

### ISSUE THREAD

**Issue by hgmart** [el-unico-match/match#16]
Como usuario de Match Plus, quiero tener la opción de dar Super Likes, los cuales indican un interés mayor que un like regular.
Criterios de aceptación

CA 1: Disponibilidad de Super Likes
Cuando un usuario de Match Plus navega en el feed.
Entonces debe tener la opción de dar Super Likes a perfiles que le interesen especialmente, destacando su perfil a los usuarios Super Liked.
CA 2: Notificación de Super Like
Cuando un usuario recibe un Super Like.
Entonces debe recibir una notificación específica, indicando quién le dio el Super Like.
CA 3: Limitación diaria de Super Likes
Aunque los likes son ilimitados, los Super Likes deben tener un límite diario.
Cuando un usuario de Match Plus alcanza el límite de Super Likes por día.
Entonces se le debe notificar que ya no puede dar más Super Likes hasta el día siguiente.

**Comment by diegofiuba** [comment]
Falta CA2
